# Generated by Django 4.1.7 on 2024-02-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_organization_options'),
        ('settings_and_conditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizations_by_about', serialize=False, to='clients.organization', verbose_name='Организация')),
                ('about', models.TextField(blank=True, verbose_name='О заводах TALANT')),
            ],
            options={
                'verbose_name': 'О заводах TALANT',
                'verbose_name_plural': 'О заводах TALANT',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizations_by_delivery', serialize=False, to='clients.organization', verbose_name='Организация')),
                ('delivery', models.TextField(blank=True, verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Условия доставки',
                'verbose_name_plural': 'Условия доставки',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizations_by_policy', serialize=False, to='clients.organization', verbose_name='Организация')),
                ('policy', models.TextField(blank=True, verbose_name='Политика обработки персональных данных')),
            ],
            options={
                'verbose_name': 'Политика обработки персональных данных',
                'verbose_name_plural': 'Политика обработки персональных данных',
            },
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee',
            field=models.TextField(blank=True, verbose_name='Условия гарантии и возврата'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organizations_by_guarantee', serialize=False, to='clients.organization', verbose_name='Организация'),
        ),
    ]
