# Generated by Django 4.1.7 on 2024-02-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0002_about_delivery_policy_alter_guarantee_guarantee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('use_up', models.BooleanField(db_index=True, default=True, verbose_name='использовать')),
                ('notification_type', models.CharField(blank=True, choices=[('confirm_registration', 'Подтверждение регистрации на сайте'), ('confirm_order', 'Подтверждение заказа клиента')], db_index=True, max_length=50, verbose_name='тип уведомления')),
            ],
            options={
                'verbose_name': 'Настройка уведомления',
                'verbose_name_plural': 'Найстройка уведомлений',
            },
        ),
    ]
