# Generated by Django 4.1.7 on 2024-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0004_auto_20240209_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metals', models.BooleanField(default=True, verbose_name='металл')),
                ('metal_finish', models.BooleanField(default=False, verbose_name='обработка металлов')),
                ('brands', models.BooleanField(default=False, verbose_name='бренд')),
                ('prod_status', models.BooleanField(default=False, verbose_name='маркетинговый статус')),
                ('collections', models.BooleanField(default=True, verbose_name='коллекции')),
                ('genders', models.BooleanField(default=False, verbose_name='для кого')),
                ('sizes', models.BooleanField(default=True, verbose_name='размеры')),
                ('gems', models.BooleanField(default=True, verbose_name='вставки')),
                ('colors', models.BooleanField(default=True, verbose_name='цвета вставок')),
                ('cuts', models.BooleanField(default=False, verbose_name='огранка')),
                ('quantity_range', models.BooleanField(default=False, verbose_name='количество вставок')),
                ('instok_range', models.BooleanField(default=False, verbose_name='остатки')),
                ('price_range', models.BooleanField(default=False, verbose_name='базовые цены')),
                ('weight_range', models.BooleanField(default=False, verbose_name='вес изделий')),
            ],
            options={
                'verbose_name': 'Настройка фильтров каталога',
                'verbose_name_plural': 'Настройка фильтров каталога',
            },
        ),
    ]
