# Generated by Django 4.1.7 on 2024-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0005_catalogfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogfilter',
            name='hide_count_of_products',
            field=models.BooleanField(default=True, verbose_name='скрывать количество изделий в фильтрах'),
        ),
    ]
