# Generated by Django 4.2.11 on 2024-03-27 09:20

from django.db import migrations

def delete_notification_rows(apps, schema_editor):
    Notifications = apps.get_model("settings_and_conditions", "Notification")
    Notifications.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0006_catalogfilter_hide_count_of_products'),
    ]

    operations = [
        migrations.RunPython(delete_notification_rows),
    ]
