# Generated by Django 4.2.11 on 2024-03-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0007_auto_20240327_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('confirm_registration', 'Подтверждение регистрации на сайте'), ('confirm_order', 'Подтверждение заказа клиента')], db_index=True, max_length=50, verbose_name='Событие')),
                ('notification', models.TextField(blank=True, verbose_name='Шаблон письма')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='settings_and_conditions.notificationtype', verbose_name='тип уведомления'),
        ),
    ]
