# Generated by Django 4.2.11 on 2024-03-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0009_notification_manager_talant_alter_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='event',
            field=models.CharField(choices=[('registration_request', 'Получение заявки на регистрацию'), ('confirm_registration', 'Подтверждение регистрации на сайте'), ('confirm_order', 'Подтверждение заказа клиента')], db_index=True, max_length=50, verbose_name='Событие'),
        ),
    ]
