# Generated by Django 4.2.11 on 2024-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0010_notificationtype_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='event',
            field=models.CharField(choices=[('registration_request', 'Получение заявки на регистрацию'), ('confirm_registration', 'Подтверждение регистрации на сайте'), ('confirm_order', 'Подтверждение заказа клиента'), ('recovery_password', 'Запрос восстановления пароля')], db_index=True, max_length=50, verbose_name='Событие'),
        ),
    ]
