# Generated by Django 4.2.11 on 2024-07-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0014_mailingofletters_template_and_more'),
        ('settings_and_conditions', '0015_alter_notificationtype_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to='mailings.notifytemplate', verbose_name='Шаблон письма'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='notification',
            field=models.TextField(blank=True, verbose_name='Содержание письма'),
        ),
    ]
