# Generated by Django 4.1.7 on 2024-10-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_and_conditions', '0018_alter_catalogfilter_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogfilter',
            old_name='collections',
            new_name='сategories',
        ),
    ]
