# Generated by Django 4.1.7 on 2024-12-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_customersegments_client'),
        ('settings_and_conditions', '0019_rename_collections_catalogfilter_сategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='promotions', serialize=False, to='clients.organization', verbose_name='Организация')),
                ('description', models.TextField(blank=True, verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
