version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: CabinetOpt
    restart: always
    command: gunicorn CabinetOpt.wsgi:application --bind 0.0.0.0:8000 --timeout 3600
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cabinet_opt

  redis:
    image: 'redis:6.2-alpine'
    restart: always
    hostname: redis
    environment:
      REDIS_PWD: '${REDIS_PWD}'
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PWD

  rqworker:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: CabinetOpt_RQWorker
    restart: always
    command: python manage.py rqworker default --with-scheduler
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

  clear:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: CabinetOpt_CL
    command: python manage.py clear_links --timeout 3600
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - web

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    #command: certonly --webroot --webroot-path=/var/www/certbot/ --email admin@talantgold.ru --agree-tos --no-eff-email -d opt.talantgold.ru
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
