version: '3.8'

services:
  web:
    build: ./
    container_name: CabinetOpt
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.stage
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cabinet_opt

  redis:
    image: 'redis:6.2-alpine'
    restart: always
    hostname: redis
    privileged: true
    ports:
      - "6379:6379"

volumes:
  postgres_data:
