# Generated by Django 4.1.7 on 2023-03-30 19:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Приоритетное направление')),
            ],
            options={
                'verbose_name': 'Приоритетное направление',
                'verbose_name_plural': 'Приоритетные направления',
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Организация')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('manager', models.CharField(max_length=150, verbose_name='ФИО менеджера')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email менеджера')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Контактный телефон менеджера')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('considered', 'Рассматривается'), ('registered', 'Зарегистрирован')], default='pending', max_length=10, verbose_name='Статус регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('priority_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_orders', to='clients.prioritydirection', verbose_name='Приоритетное направление')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
            },
        ),
    ]
