# Generated by Django 4.1.7 on 2023-07-08 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Организация')),
                ('inn', models.CharField(db_index=True, max_length=12, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('locked', 'Заблокирован')], default='active', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Контактный телефон')),
                ('login', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Персональный менеджер',
                'verbose_name_plural': 'Персональные менеджеры',
            },
        ),
        migrations.CreateModel(
            name='PriorityDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Приоритетное направление')),
                ('identifier_1C', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С')),
            ],
            options={
                'verbose_name': 'Приоритетное направление',
                'verbose_name_plural': 'Приоритетные направления',
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_details', serialize=False, to='clients.client', verbose_name='Клиент')),
                ('city', models.CharField(blank=True, default='', max_length=150, verbose_name='Город')),
                ('legal_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Юридический адерс')),
                ('shoping_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'наличная'), ('cashless', 'безналичная')], db_index=True, default='cash', max_length=10, verbose_name='Вариант оплаты')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Организация')),
                ('inn', models.CharField(db_index=True, max_length=12, verbose_name='ИНН')),
                ('name_of_manager', models.CharField(blank=True, max_length=150, verbose_name='ФИО менеджера')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email менеджера')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Контактный телефон менеджера')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('considered', 'Рассматривается'), ('registered', 'Зарегистрирован')], default='pending', max_length=10, verbose_name='Статус регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('priority_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_orders', to='clients.prioritydirection', verbose_name='Приоритетное направление')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
            },
        ),
    ]
