# Generated by Django 4.1.7 on 2023-07-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clients', to=settings.AUTH_USER_MODEL, verbose_name='Утвержден'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ManyToManyField(related_name='clients_by_managers', to='clients.manager', verbose_name='Персональные менеджеры'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.registrationorder', verbose_name='Заявка на регистрацию'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clients', to=settings.AUTH_USER_MODEL, verbose_name='Изменен'),
        ),
    ]
