# Generated by Django 4.1.7 on 2023-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20230330_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationorder',
            name='inn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
    ]
