# Generated by Django 4.1.7 on 2023-05-11 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20230330_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Организация')),
                ('inn', models.CharField(db_index=True, max_length=12, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_clients', to=settings.AUTH_USER_MODEL, verbose_name='Утвержден')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Контактный телефон')),
                ('login', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Персональный менеджер',
                'verbose_name_plural': 'Персональные менеджеры',
            },
        ),
        migrations.RemoveField(
            model_name='registrationorder',
            name='manager',
        ),
        migrations.AddField(
            model_name='registrationorder',
            name='name_of_manager',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО менеджера'),
        ),
        migrations.AlterField(
            model_name='registrationorder',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contact_details', serialize=False, to='clients.client', verbose_name='Клиент')),
                ('city', models.CharField(blank=True, default='', max_length=150, verbose_name='Город')),
                ('legal_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Юридический адерс')),
                ('shoping_address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес доставки')),
                ('payment_type', models.CharField(choices=[('cash', 'наличная'), ('cashless', 'безналичная')], db_index=True, default='cash', max_length=10, verbose_name='Вариант оплаты')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ManyToManyField(related_name='clients_by_managers', to='clients.manager', verbose_name='Персональные менеджеры'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.registrationorder', verbose_name='Заявка на регистрацию'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clients', to=settings.AUTH_USER_MODEL, verbose_name='Изменен'),
        ),
    ]
