# Generated by Django 4.1.7 on 2023-06-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_manager_remove_registrationorder_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritydirection',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
    ]
