# Generated by Django 4.1.7 on 2023-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_prioritydirection_identifier_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('locked', 'Заблокирован')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
