# Generated by Django 4.1.7 on 2023-08-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_registrationorder_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationorder',
            old_name='inn',
            new_name='identification_number',
        ),
    ]
