# Generated by Django 4.1.7 on 2023-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_registrationorder_name_of_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationorder',
            name='manager',
        ),
    ]
