# Generated by Django 4.1.7 on 2023-10-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_registrationorder_manager_talant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Персональный менеджер', 'verbose_name_plural': 'Персональные менеджеры'},
        ),
    ]
