# Generated by Django 4.1.7 on 2023-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_registrationorder_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Персональный менеджер', 'verbose_name_plural': 'Персональные менеджеры'},
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.ManyToManyField(related_name='clients_by_managers', to='clients.manager', verbose_name='Персональные менеджеры'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='surname',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
    ]
