# Generated by Django 4.1.7 on 2023-04-10 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_manager_options_alter_client_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата обновления'),
        ),
    ]
