# Generated by Django 4.1.7 on 2023-10-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_priority_direction'),
        ('catalog', '0032_alter_product_brand'),
        ('clients', '0007_alter_client_options_alter_manager_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationorder',
            name='priority_direction',
        ),
        migrations.DeleteModel(
            name='PriorityDirection',
        ),
    ]
