# Generated by Django 4.1.7 on 2023-10-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_remove_registrationorder_priority_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Менеджер клиента', 'verbose_name_plural': 'Менеджеры клиента'},
        ),
        migrations.AddField(
            model_name='client',
            name='manager_talant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_by_talants_managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер ЮИ-Трейд'),
        ),
        migrations.AlterField(
            model_name='registrationorder',
            name='manager_talant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_talant', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер ЮИ-Трейд'),
        ),
    ]
