# Generated by Django 4.1.7 on 2024-02-07 09:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_manager_options_client_manager_talant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адерс')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Наша ошганизация',
                'verbose_name_plural': 'Наши юридические лица',
            },
        ),
    ]
