# Generated by Django 4.1.7 on 2024-02-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Наша организация', 'verbose_name_plural': 'Наша организация'},
        ),
    ]
