# Generated by Django 4.2.11 on 2024-03-27 19:08

from django.db import migrations

def create_managers(apps, schema_editor):
    Clients = apps.get_model("clients", "Client")
    clients = Clients.objects.all()
    for client in clients:
        registration_order = client.registration_order
        client.manager.all().update(
            name=registration_order.name,
            email = registration_order.email,
            phone = registration_order.phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_manager_options_remove_manager_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(create_managers, migrations.RunPython.noop),
    ]
