# Generated by Django 4.2.11 on 2024-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20240327_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('considered', 'Рассматривается'), ('registered', 'Зарегистрирован'), ('canceled', 'Отменен')], default='pending', max_length=10, verbose_name='Статус регистрации'),
        ),
    ]
