# Generated by Django 4.2.11 on 2024-05-16 11:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_authorizationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='доп. email'),
        ),
        migrations.AddField(
            model_name='organization',
            name='additional_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='доп. телефон'),
        ),
    ]
