# Generated by Django 4.2.11 on 2024-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_organization_additional_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='additional_email',
            field=models.CharField(blank=True, max_length=150, verbose_name='доп. email'),
        ),
    ]
