# Generated by Django 4.2.11 on 2024-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_manager_email_alter_manager_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('client', models.ManyToManyField(related_name='client_segments', to='clients.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Сегмент клиентов',
                'verbose_name_plural': 'Сегменты клиентов',
            },
        ),
    ]
