# Generated by Django 4.2.11 on 2024-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_customersegments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersegments',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='client_segments', to='clients.client', verbose_name='Клиенты'),
        ),
    ]
