# Generated by Django 4.1.7 on 2025-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images', verbose_name='Карта'),
        ),
    ]
