# Generated by Django 4.1.7 on 2023-06-14 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Металл'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_content',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Проба'),
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cost', to='catalog.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Стоимость изделия',
                'verbose_name_plural': 'Стоимость изделий',
            },
        ),
    ]
