# Generated by Django 4.1.7 on 2023-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_price_discount_product_metal_product_metal_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('-', '-')], db_index=True, default='-', max_length=20, verbose_name='Гендер'),
        ),
    ]
