# Generated by Django 4.1.7 on 2023-06-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('novelty', 'Новинка'), ('order', 'Заказ'), ('hit', 'Хит'), ('sale', 'Распродажа')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('М', 'мужской'), ('Ж', 'женский'), ('-', 'мужской, женский')], db_index=True, default='-', max_length=10, verbose_name='Гендер'),
        ),
    ]
