# Generated by Django 4.1.7 on 2023-07-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_collectiongroup_remove_product_price_per_gr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiongroup',
            options={'verbose_name': 'Группа коллекций', 'verbose_name_plural': 'Группы коллекций'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='catalog.collectiongroup', verbose_name='Группа'),
        ),
    ]
