# Generated by Django 4.1.7 on 2023-07-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_prioritydirection_options_and_more'),
        ('catalog', '0005_alter_collectiongroup_options_alter_collection_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='catalog.product', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.pricetype', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_prices', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='clients.prioritydirection', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_products', to='catalog.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='stockandcost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_and_costs', to='catalog.product', verbose_name='Номенклатура'),
        ),
    ]
