# Generated by Django 4.1.7 on 2023-07-17 08:08

from django.db import migrations


def add_bases_price_type(apps, schema_editor):
    PriceType = apps.get_model("catalog", "PriceType")

    new_obj = PriceType(name="Базовая")
    new_obj.save()

    new_obj = PriceType(name="Выгода")
    new_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_price_start_at_alter_stockandcost_cost'),
    ]

    operations = [
        migrations.RunPython(add_bases_price_type),
    ]

