# Generated by Django 4.1.7 on 2023-07-18 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230717_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Органка',
                'verbose_name_plural': 'Виды огранки',
            },
        ),
        migrations.CreateModel(
            name='PreciousStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('novelty', 'NEW!'), ('order', 'ЗАКАЗ'), ('hit', 'ХИТ'), ('sale', 'ВЫГОДНО')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Цвет')),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Комментарий')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('cut_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_types', to='catalog.cuttype', verbose_name='Огранка')),
                ('precious_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precious_stones', to='catalog.preciousstone', verbose_name='Камни')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gem_sets', to='catalog.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Вставка',
                'verbose_name_plural': 'Вставки',
            },
        ),
    ]
