# Generated by Django 4.1.7 on 2023-07-18 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_cuttype_preciousstone_alter_product_status_gemset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AddField(
            model_name='preciousstone',
            name='short_title',
            field=models.CharField(blank=True, max_length=10, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='gemset',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес, кр'),
        ),
    ]
