# Generated by Django 4.1.7 on 2023-07-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_options_preciousstone_short_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuttype',
            options={'verbose_name': 'Огранка', 'verbose_name_plural': 'Виды огранки'},
        ),
        migrations.CreateModel(
            name='ProductsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_set', to='catalog.product', verbose_name='Комплектующее')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Состав',
            },
        ),
    ]
