# Generated by Django 4.1.7 on 2023-07-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_cuttype_options_productsset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Номенклатура'),
        ),
    ]
