# Generated by Django 4.1.7 on 2023-07-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_productsset_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsset',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_of_products', to='catalog.product', verbose_name='Комплектующее'),
        ),
        migrations.CreateModel(
            name='SimilarProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Номенклатура')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='similar_products', to='catalog.product', verbose_name='Аналог')),
            ],
            options={
                'verbose_name': 'Аналог',
                'verbose_name_plural': 'Аналоги',
            },
        ),
    ]
