# Generated by Django 4.1.7 on 2023-08-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockandcost',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='catalog.size', verbose_name='Размер'),
        ),
    ]
