# Generated by Django 4.1.7 on 2023-08-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_stockandcost_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='stockandcost',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='catalog.size', verbose_name='Размер'),
        ),
    ]
