# Generated by Django 4.1.7 on 2023-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_size_name_alter_stockandcost_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiongroup',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
    ]
