# Generated by Django 4.1.7 on 2023-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_collectiongroup_identifier_1c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiongroup',
            name='identifier_1C',
        ),
        migrations.AddField(
            model_name='preciousstone',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
    ]
