# Generated by Django 4.1.7 on 2023-08-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_collectiongroup_identifier_1c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Гендер')),
            ],
            options={
                'verbose_name': 'Гендер',
                'verbose_name_plural': 'Виды гендера',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_gender', to='catalog.gender', verbose_name='Гендер'),
        ),
    ]
