# Generated by Django 4.1.7 on 2023-08-24 10:33

from django.db import migrations

def add_default_genders(apps, schema_editor):
    Gender = apps.get_model("catalog", "Gender")

    new_obj = Gender(name="для мужчин")
    new_obj.save()

    new_obj = Gender(name="для женщин")
    new_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_gender_alter_product_gender'),
    ]

    operations = [
        migrations.RunPython(add_default_genders),
    ]
