# Generated by Django 4.1.7 on 2023-09-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_gender_options_product_metal_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gemset',
            old_name='color',
            new_name='gem_color',
        ),
        migrations.RenameField(
            model_name='gemset',
            old_name='quantity',
            new_name='gem_quantity',
        ),
        migrations.RenameField(
            model_name='gemset',
            old_name='weight',
            new_name='gem_weight',
        ),
    ]
