# Generated by Django 4.1.7 on 2023-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_gemset_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Обработка металла')),
            ],
            options={
                'verbose_name': 'Вид обработки металла',
                'verbose_name_plural': 'Виды обработки металла',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='metal_finish',
        ),
        migrations.AddField(
            model_name='product',
            name='metal_finish',
            field=models.ManyToManyField(related_name='products_by_gender', to='catalog.metalfinish', verbose_name='Обработка металла'),
        ),
    ]
