# Generated by Django 4.1.7 on 2023-09-09 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_metalfinish_remove_product_metal_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Дизайн')),
            ],
            options={
                'verbose_name': 'Дизайн изделия',
                'verbose_name_plural': 'Дизайны изделий',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Подарок')),
            ],
            options={
                'verbose_name': 'Подарок',
                'verbose_name_plural': 'Подарки',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bracelet_width',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина браслета'),
        ),
        migrations.AddField(
            model_name='product',
            name='chain_width',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина цепи'),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_type_bracelet',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Тип и размер замка браслетов'),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_type_chain',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Тип и размер замка цепей'),
        ),
        migrations.AddField(
            model_name='product',
            name='lock_type_earings',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Тип и размер замка серег'),
        ),
        migrations.AddField(
            model_name='product',
            name='q_borders_c_b',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество граней'),
        ),
        migrations.AddField(
            model_name='product',
            name='str_color',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Цвет строкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ManyToManyField(related_name='products_by_design', to='catalog.design', verbose_name='Дизайн'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift',
            field=models.ManyToManyField(related_name='products_by_gift', to='catalog.gift', verbose_name='Подарок'),
        ),
    ]
