# Generated by Django 4.1.7 on 2023-10-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'товар'), ('service', 'услуга'), ('gift_сertificate', 'подарочный сертификат')], db_index=True, default='product', max_length=20, verbose_name='Тип'),
        ),
    ]
