# Generated by Django 4.1.7 on 2023-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOfStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('site', models.CharField(blank=True, max_length=10, verbose_name='наименование для сайта')),
                ('filter', models.CharField(blank=True, max_length=10, verbose_name='наименование для фильтра')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.AddField(
            model_name='cuttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cut_type_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.ManyToManyField(related_name='products_by_style', to='catalog.style', verbose_name='Стиль'),
        ),
    ]
