# Generated by Django 4.1.7 on 2023-11-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_gemset_color_filter_gemset_precious_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorofstone',
            old_name='filter',
            new_name='name_of_filter',
        ),
    ]
