# Generated by Django 4.1.7 on 2023-12-14 17:23

import catalog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_product_show_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=catalog.models.TrimCharField(blank=True, db_index=True, max_length=50, verbose_name='Металл'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metal_content',
            field=catalog.models.TrimCharField(blank=True, db_index=True, max_length=30, verbose_name='Проба'),
        ),
    ]
