# Generated by Django 4.1.7 on 2023-12-14 17:32

from django.db import migrations

def save_products(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for entry in Product.objects.all():
        entry.metal = entry.metal.strip()
        entry.metal_content = entry.metal_content.strip()
        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_product_metal_alter_product_metal_content'),
    ]

    operations = [
        migrations.RunPython(save_products, migrations.RunPython.noop),
    ]
