# Generated by Django 4.1.7 on 2023-12-14 17:59

import catalog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_product_metal_alter_product_metal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=catalog.models.TrimCharField(blank=True, db_index=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='str_color',
            field=catalog.models.TrimCharField(blank=True, db_index=True, max_length=50, verbose_name='Цвет строкой'),
        ),
    ]
