# Generated by Django 4.1.7 on 2023-12-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20231214_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cut_type_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение огранки',
                'verbose_name_plural': 'Изображения видов огранки',
            },
        ),
        migrations.RemoveField(
            model_name='cuttype',
            name='image',
        ),
        migrations.AddField(
            model_name='cuttype',
            name='short_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Краткое наименование'),
        ),
    ]
