# Generated by Django 4.1.7 on 2023-12-25 15:09

from django.db import migrations
from django.core.files.base import ContentFile


def add_cut_type_images(apps, schema_editor):
    cut_types = {
        'Круг'         : 'circle.png',
        'Груша'        : 'pear.png',
        'Овал'         : 'oval.png',
        'Маркиз'       : 'marquis.png',
        'Сердце'       : 'heart.png',
        'Квадрат'      : 'square.png',
        'Багет'        : 'baguette.png',
        'Прямоугольник': 'rectangle.png',
    }

    CutTypeImage = apps.get_model("catalog", "CutTypeImage")

    for key, val in cut_types.items():
        new_obj = CutTypeImage(name=key)
        with open(f'./media/cut_type_images/{val}', 'rb') as file_handler:
            image_data = file_handler.read()
            new_obj.image.save(val, ContentFile(image_data))
        new_obj.save()


def delete_cut_type_images(apps, schema_editor):
    CutTypeImage = apps.get_model("catalog", "CutTypeImage")
    CutTypeImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_cuttypeimage_remove_cuttype_image_and_more'),
    ]

    operations = [
        migrations.RunPython(add_cut_type_images, delete_cut_type_images)
    ]
