# Generated by Django 4.2.11 on 2024-04-04 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_cuttype_cut_type_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Вид коллекции', 'verbose_name_plural': 'Виды коллекций'},
        ),
        migrations.AlterModelOptions(
            name='collectiongroup',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AddField(
            model_name='collectiongroup',
            name='order',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порядок'),
        ),
    ]
