# Generated by Django 4.2.11 on 2024-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('novelty', 'NEW!'), ('hit', 'ХИТ'), ('sale', 'SALE'), ('profit', 'ВЫГОДНО'), ('exclusive', 'ЭКСКЛЮЗИВ')], db_index=True, max_length=20, verbose_name='Статус'),
        ),
    ]
