# Generated by Django 4.1.7 on 2024-10-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20241015_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сategory',
            options={'verbose_name': 'Подгруппа товара', 'verbose_name_plural': 'Подгруппы товаров'},
        ),
        migrations.AlterModelOptions(
            name='сategorygroup',
            options={'verbose_name': 'Группа товара', 'verbose_name_plural': 'Группы товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='сategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='сategory_products', to='catalog.сategory', verbose_name='Группа'),
        ),
    ]
