# Generated by Django 4.1.7 on 2024-10-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20241022_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
