# Generated by Django 4.1.7 on 2024-10-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_remove_product_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='identifier_1C',
        ),
        migrations.AddField(
            model_name='product',
            name='сollection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='сollection_products', to='catalog.collection', verbose_name='Коллекция'),
        ),
        migrations.DeleteModel(
            name='CollectionGroup',
        ),
    ]
