# Generated by Django 4.1.7 on 2024-10-23 14:36

from django.db import migrations


def empty_collections(apps, schema_editor):

    Collection = apps.get_model("catalog", "Collection")
    Collection.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_alter_collection_options_remove_collection_discount_and_more'),
    ]

    operations = [
        migrations.RunPython(empty_collections),
    ]
