# Generated by Django 4.1.7 on 2024-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_alter_productrating_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlikeProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('alike_product', models.ManyToManyField(related_name='alike_products', to='catalog.product', verbose_name='Похожий товар')),
            ],
            options={
                'verbose_name': 'Группа похожести',
                'verbose_name_plural': 'Группы похожести',
            },
        ),
    ]
