# Generated by Django 4.2.11 on 2024-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Тема')),
                ('html_content', models.TextField(verbose_name='Содержание письма')),
            ],
            options={
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Исходящие письма',
            },
        ),
    ]
