# Generated by Django 4.2.11 on 2024-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmail',
            name='sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отправлено'),
        ),
    ]
