# Generated by Django 4.2.11 on 2024-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_outgoingmail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmail',
            name='email',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Email получателя'),
        ),
    ]
