# Generated by Django 4.2.11 on 2024-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_outgoingmail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmail',
            name='sent',
        ),
        migrations.AddField(
            model_name='outgoingmail',
            name='sent_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата отправки'),
        ),
    ]
