# Generated by Django 4.2.11 on 2024-07-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_manager_email_alter_manager_login'),
        ('mailings', '0004_remove_outgoingmail_sent_outgoingmail_sent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingOfLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование рассылки')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Тема рассылки')),
                ('template', models.TextField(blank=True, verbose_name='Шаблон')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('sent', 'К отправке'), ('new', 'Новая')], db_index=True, default='Новая', max_length=20, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(related_name='mailing_clients', to='clients.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
