# Generated by Django 4.2.11 on 2024-07-11 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailingofletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingofletters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingofletters',
            name='status',
            field=models.CharField(choices=[('completed', 'Выполнено'), ('sent', 'К отправке'), ('new', 'Новая')], db_index=True, default='new', max_length=20, verbose_name='Статус рассылки'),
        ),
    ]
