# Generated by Django 4.2.11 on 2024-07-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_mailingofletters_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmail',
            name='mailing_of_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_mail_by_mailing_lists', to='mailings.mailingofletters', verbose_name='Рассылка'),
        ),
    ]
