# Generated by Django 4.2.11 on 2024-07-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_outgoingmail_mailing_of_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmail',
            name='mailing_of_letter',
        ),
    ]
