# Generated by Django 4.2.11 on 2024-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_remove_outgoingmail_mailing_of_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmail',
            name='email',
            field=models.CharField(db_index=True, max_length=1024, verbose_name='Email получателя'),
        ),
    ]
