# Generated by Django 4.2.11 on 2024-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_customersegments_client'),
        ('mailings', '0009_alter_outgoingmail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingofletters',
            name='client',
        ),
        migrations.AddField(
            model_name='mailingofletters',
            name='segment',
            field=models.ManyToManyField(related_name='mailing_segments', to='clients.customersegments', verbose_name='Сегмент клиентов'),
        ),
    ]
