# Generated by Django 4.2.11 on 2024-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0011_notifytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifytemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='footer_template',
            field=models.TextField(blank=True, verbose_name='Шаблон подвала'),
        ),
        migrations.AddField(
            model_name='notifytemplate',
            name='header_template',
            field=models.TextField(blank=True, verbose_name='Шаблон заголовка'),
        ),
    ]
