# Generated by Django 4.2.11 on 2024-07-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0020_alter_customersegments_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, verbose_name='Идентификатор записи')),
                ('key', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ключ')),
                ('attributes', models.JSONField(blank=True, default=dict, null=True, verbose_name='Атрибуты')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_clients', to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_managers', to='clients.manager', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
