# Generated by Django 4.2.11 on 2024-08-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=12, unique=True)),
                ('path', models.CharField(max_length=255, verbose_name='url')),
                ('param', models.JSONField(blank=True, default=dict, null=True, verbose_name='Параметры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
