# Generated by Django 4.2.11 on 2024-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
    ]
