# Generated by Django 4.1.7 on 2023-04-24 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Фото издения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('articul', models.CharField(blank=True, max_length=200, verbose_name='Артикул')),
                ('price_per_gr', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за грамм')),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток')),
                ('available_for_order', models.BooleanField(db_index=True, default=False, verbose_name='Доступен для заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('product_type', models.CharField(choices=[('product', 'товар'), ('service', 'услуга'), ('gift_сertificate', 'подарочный сертификат')], db_index=True, default='product', max_length=20, verbose_name='Тип номенклатуры')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='orders.collection', verbose_name='Коллекция')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_by_images', to='orders.productimage', verbose_name='Фото')),
            ],
        ),
    ]
