# Generated by Django 4.1.7 on 2023-04-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_contactdetail_id_alter_contactdetail_client'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_by_brands', to='clients.prioritydirection', verbose_name='Бренд'),
        ),
    ]
