# Generated by Django 4.1.7 on 2023-05-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_manager_remove_registrationorder_manager_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices_by_client', to='clients.client', verbose_name='Клиент'),
        ),
    ]
