# Generated by Django 4.1.7 on 2023-07-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_prioritydirection_options_and_more'),
        ('catalog', '0006_alter_price_product_alter_price_type_and_more'),
        ('orders', '0002_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_oders', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_oders', to='clients.manager', verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_type_orders', to='catalog.pricetype', verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='catalog.product', verbose_name='Номенклатура'),
        ),
    ]
