# Generated by Django 4.1.7 on 2023-04-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_product_image_productimage_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенкулатура'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Фото номенклатуры'),
        ),
    ]
