# Generated by Django 4.1.7 on 2023-08-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_stockandcost_size'),
        ('orders', '0003_alter_order_client_alter_order_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_orders', to='catalog.size', verbose_name='Размер'),
        ),
    ]
