# Generated by Django 4.1.7 on 2023-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='num_in_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='номер в ЮТД'),
        ),
    ]
