# Generated by Django 4.1.7 on 2023-04-27 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('796', 'штук'), ('163', 'грамм')], db_index=True, default='796', max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('start_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата начала действия')),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата окончания действия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.product', verbose_name='Номенклатура')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_by_type', to='orders.pricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
