# Generated by Django 4.1.7 on 2023-04-29 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_contactdetail_id_alter_contactdetail_client'),
        ('orders', '0006_pricetype_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('introductory', 'Предварительный'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('shipment', 'Отгрузка'), ('completed', 'Завершен')], db_index=True, default='introductory', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oders_by_client', to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oders_by_manager', to='clients.manager', verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('штук', 'штук'), ('грамм', 'грамм')], db_index=True, default='грамм', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('штук', 'штук'), ('грамм', 'грамм')], db_index=True, default='грамм', max_length=20, verbose_name='Единица измерения')),
                ('series', models.CharField(blank=True, max_length=50, verbose_name='Серия')),
                ('uin', models.CharField(blank=True, max_length=50, verbose_name='УИН')),
                ('weight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_by_price', to='orders.pricetype', verbose_name='Тип цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.product', verbose_name='Номенклатура')),
            ],
        ),
    ]
