# Generated by Django 4.1.7 on 2023-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='identifier_1C',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Идентификатор 1С'),
        ),
    ]
