# Generated by Django 4.1.7 on 2023-05-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_product_unit_alter_price_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Имя файла'),
        ),
    ]
